version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=False
      - SECRET_KEY=change_me_in_production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/payslip_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn payslip.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payslip_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Celery services commented out until Celery is properly configured
  # celery:
  #   build: .
  #   restart: always
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #     - redis
  #     - web
  #   environment:
  #     - DEBUG=False
  #     - SECRET_KEY=change_me_in_production
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/payslip_db
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   command: celery -A payslip worker -l info

  # celery-beat:
  #   build: .
  #   restart: always
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #     - redis
  #     - web
  #   environment:
  #     - DEBUG=False
  #     - SECRET_KEY=change_me_in_production
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/payslip_db
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   command: celery -A payslip beat -l info

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: 