version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: payslip_prod
    command: gunicorn payslip.wsgi_prod:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - redis
      - celery
      - celery-beat

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: payslip_celery_prod
    command: celery -A payslip worker -l info
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: payslip_celerybeat_prod
    command: celery -A payslip beat -l info
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - redis

volumes:
  static_volume:
  media_volume:
  redis_data: 