# Generated by Django 4.2.8 on 2025-03-01 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
