# Generated by Django 4.2.8 on 2025-03-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate amount', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('monthly', 'Monthly Salary'), ('hourly', 'Hourly Rate')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly base salary amount', max_digits=12, null=True),
        ),
    ]
