# Generated by Django 4.2.8 on 2025-03-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_loanpayment_payment_number_loanpayment_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
    ]
