# Generated by Django 4.2.8 on 2025-03-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_income', models.DecimalField(decimal_places=2, help_text='Minimum income for this tax bracket', max_digits=12)),
                ('max_income', models.DecimalField(decimal_places=2, default=0, help_text='Maximum income for this tax bracket (0 for no upper limit)', max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as a percentage (e.g., 15.00 for 15%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Tier',
                'verbose_name_plural': 'Tax Tiers',
                'ordering': ['min_income'],
            },
        ),
    ]
