# Generated by Django 4.2.8 on 2025-03-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_employee_id'),
        ('payroll', '0002_taxtier'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayrollTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_template', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayrollTemplateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_deduction', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.employeepayrolltemplate')),
            ],
            options={
                'verbose_name_plural': 'Template entries',
                'ordering': ['-is_deduction', 'name'],
            },
        ),
    ]
