from django.urls import path
from .views import (
    PayrollListView,
    PayrollDetailView,
    PayrollCreateView,
    PayrollUpdateView,
    PayrollDeleteView,
    PayrollProcessView,
    generate_payslip_pdf_view,
    add_payroll_entry,
    delete_payroll_entry,
    PayrollPeriodListView,
    PayrollPeriodCreateView,
    PayrollPeriodUpdateView,
    PayrollPeriodDeleteView,
    PayrollItemListView,
    PayrollItemCreateView,
    PayrollItemUpdateView,
    PayrollItemDeleteView,
    check_periods,
    TaxTierListView,
    TaxTierCreateView,
    TaxTierUpdateView,
    TaxTierDeleteView,
    bulk_update_payroll_status,
)

urlpatterns = [
    path('', PayrollListView.as_view(), name='payroll_list'),
    path('<int:pk>/', PayrollDetailView.as_view(), name='payroll_detail'),
    path('create/', PayrollCreateView.as_view(), name='payroll_create'),
    path('<int:pk>/edit/', PayrollUpdateView.as_view(), name='payroll_update'),
    path('<int:pk>/delete/', PayrollDeleteView.as_view(), name='payroll_delete'),
    path('<int:pk>/pdf/', generate_payslip_pdf_view, name='generate_payslip_pdf'),
    path('process/', PayrollProcessView.as_view(), name='process_payroll'),
    path('bulk-update-status/', bulk_update_payroll_status, name='bulk_update_payroll_status'),
    path('<int:pk>/entry/add/', add_payroll_entry, name='add_payroll_entry'),
    path('entry/<int:pk>/delete/', delete_payroll_entry, name='delete_payroll_entry'),
    path('periods/', PayrollPeriodListView.as_view(), name='period_list'),
    path('periods/create/', PayrollPeriodCreateView.as_view(), name='period_create'),
    path('periods/<int:pk>/edit/', PayrollPeriodUpdateView.as_view(), name='period_update'),
    path('periods/<int:pk>/delete/', PayrollPeriodDeleteView.as_view(), name='period_delete'),
    path('items/', PayrollItemListView.as_view(), name='item_list'),
    path('items/create/', PayrollItemCreateView.as_view(), name='item_create'),
    path('items/<int:pk>/edit/', PayrollItemUpdateView.as_view(), name='item_update'),
    path('items/<int:pk>/delete/', PayrollItemDeleteView.as_view(), name='item_delete'),
    path('check-periods/', check_periods, name='check_periods'),
    # Tax Tier URLs
    path('tax-tiers/', TaxTierListView.as_view(), name='tax_tier_list'),
    path('tax-tiers/create/', TaxTierCreateView.as_view(), name='tax_tier_create'),
    path('tax-tiers/<int:pk>/edit/', TaxTierUpdateView.as_view(), name='tax_tier_update'),
    path('tax-tiers/<int:pk>/delete/', TaxTierDeleteView.as_view(), name='tax_tier_delete'),
] 